sudo: required

addons:

  chrome: stable



language: node_js

node_js:

  - "8"



branches:

  only:

    - master

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"


before_script:

  - npm install -g @angular/cli
No captured browser, open http://localhost:9876/



script:

  - ng build --prod --aot


  - ng test
  